version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: transcendence_db
    restart: always
    environment:
      POSTGRES_USER: aymane
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: fitness_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: