version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: transcendence_db
    restart: always
    environment:
      POSTGRES_USER: aymane
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: fitness_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transcendence_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://aymane:supersecretpassword@postgres:5432/fitness_db?schema=public"
      JWT_SECRET: "dev-secret-key"
      PORT: 3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transcendence_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pgdata: